#NUMPY

Numpy(numerical python) is a powerful library in python for numerical and matrix computations.it supports multidimensional arrays and matrics by enabling to perform different mathematical functions on it....

before going to use, we need to install the Numpy library we can use pip(pip install package), like pip install numpy.


In [ ]:
pip install numpy

After completing the installation of numpy library, we need to import the library by using import statement. ex: import numpy along with we will perform some basic operations like creation, arithmetic operations, and element wise operations etc..

**Array creation**



In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


Arrays in Numpy are crated using np.array()

**Array types**

*   1D Array:one dimensional array
*   2D Array:two dimensional array or matrix
*   nD Array:multi dimensional arrays

In [ ]:
oneD_array=np.array([1,2,3,4,5])
print('1 dimensional array',oneD_array)
twoD_array=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print('2 dimensional array')
print(twoD_array)

1 dimensional array [1 2 3 4 5]
2 dimensional array
[[1 2 3 4 5]
 [5 6 7 8 9]]


**Array Attributes**


*   arr.shape: Returns rows X columns of array
*   arr.dtype: Returns datatype of array
*   arr.size: Returns size of array by no of elements
*   arr.ndim: Returns n dimensions of an array


In [ ]:
print('shape of an array:',twoD_array.shape)
print('data type of an array:',twoD_array.dtype)
print('size of an array:',twoD_array.size)
print('dimension of an array:',twoD_array.ndim)

shape of an array: (2, 5)
data type of an array: int64
size of an array: 10
dimension of an array: 2


**Array Initialization**

*   zeros and ones: Initializes zeros and ones
*   empty array: Creates an empty array with uninitialized values
*   arange and linspace: Intializes values between range

In [ ]:
zeros=np.zeros((2,3))
print(zeros)# initialize values with zeros
ones=np.ones((3,3))
print('array of ones')
print(ones,end='\n')# initialize values wiyth ones
arange=np.arange(1,10,2)
print('array between 1 to 10')
print(arange)
linspace=np.linspace(0,1,5)
print('initialization of an array by equal width between 0 to 1')
print(linspace)

[[0. 0. 0.]
 [0. 0. 0.]]
array of ones
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
array between 1 to 10
[1 3 5 7 9]
initialization of an array by equal width between 0 to 1
[0.   0.25 0.5  0.75 1.  ]


The difference between range() and arange():

*range()*: range is a built-in Python function used to generate a sequence of numbers. It is often used in loops.

*Parameters*:

*   start: The starting value of the sequence (inclusive).
*   stop: The end value of the sequence (exclusive).
*   step: The difference between each pair of consecutive values (default is 1)

 Data Type: range returns a range object, which is an immutable sequence of integers.

*arange()*: arange is a NumPy function used to generate arrays with evenly spaced values. It is more flexible than range.

same parameters for arange also

Data Type: arange returns a NumPy array, which can hold integers, floats, or other data types.


**Indexing and slicing**


In [ ]:
print('original array',arr)
print(arr[0]) #first element
print(arr[-1]) #last element
print(arr[0:3]) #slicing from index 0 to 3

original array [1 2 3 4 5]
1
5
[1 2 3]


*boolean indexing*

In [ ]:
arr[arr>3]

array([4, 5])

**Array operations**

*Element wise operations*: Nuumpy support vectorized computations, doesn't need any loops to perform element wise operations.

*Matrix operations*: It is achieved by numpy.dot() to perform multiplication on two matrices..

*Aggregation functions*: Built in functions which are performed on entire arrays


In [ ]:
#Element wise operations
print(arr)
print(arr+1) #adds 1 to every element in an array with out need of loops
print(arr*2) #mul 2 to every element in an array

[1 2 3 4 5]
[2 3 4 5 6]
[ 2  4  6  8 10]


*Matrix operation*

In [ ]:
arr1=np.array([[1,2],[2,3]]) # 2X2 array
arr2=np.array([[3,4],[4,5]]) #2X2 array
print(np.dot(arr1,arr2)) # multiplicaton of two matrix

[[11 14]
 [18 23]]


*Aggregation functions*

In [ ]:
print('original array',arr)
print('sum of array',np.sum(arr))
print('mean of array',np.mean(arr))
print('standard deviation',np.std(arr))
print('maximum value of an array',np.max(arr))
print('minimum value of an array',np.min(arr))

original array [1 2 3 4 5]
sum of array 15
mean of array 3.0
standard deviation 1.4142135623730951
maximum value of an array 5
minimum value of an array 1


**Advanced operations**

*Broadcasting*: Broadcasting allows Numpy to perform operations on different shapes of arrays

*Reshaping*: Reshape() will change the shape of array as we specified but product of shape of an array and size of an array should be equal..

*concatenation*: combine arrays into single array

*splitting*: split array into n parts, where n is a number we are specified..

*Transpose*: convert rows into columns or vice versa

In [ ]:
#Broadcasting
a=np.array([[1],[2],[3]]) #3X1
b=np.array([10,20,30,40]) #1X4
a+b #3X4

array([[11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43]])

*Explanation*

Rules of Broadcasting:

Broadcasting follows specific rules to determine whether two arrays are compute for broadcasting or not.

Rule 1: Matching Dimensions: If two arrays differ in their number of dimensions, the shape of the smaller array is padded with ones on its left side (beginning) until both arrays have the same number of dimensions.

Rule 2: Compatibility: After adjusting dimensions, two dimensions are compatible

if
They are equal, or
One of them is 1.

a (broadcast):[[1 1 1 1],[2 2 2 2],[3 3 3 3]]

b (broadcast):[[10 20 30 40],[10 20 30 40],[10 20 30 40]]

result: a+b=[[11 21 31 41],[12 22 32 42],[13 23 33 43]]

In [ ]:
# Reshappe
a=np.array([1,2,3,4])
print(a)
print(a.reshape((2,2)))

[1 2 3 4]
[[1 2]
 [3 4]]


*note*: The size of a array and product of shape should be equal

In [ ]:
#cocatenation
a=np.array([[10,20,30],[40,50,60]])
b=np.array([[1,2,3],[4,5,6]])
np.concatenate((a,b))

array([[10, 20, 30],
       [40, 50, 60],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [ ]:
#splitting
print(a) # previous arrray
np.split(a,2)

[[10 20 30]
 [40 50 60]]


[array([[10, 20, 30]]), array([[40, 50, 60]])]

In [ ]:
#Transpose matrix
a=np.array([[1,2,3],[4,5,6]])
print(a)
print('transpose')
print(a.T)

[[1 2 3]
 [4 5 6]]
transpose
[[1 4]
 [2 5]
 [3 6]]


*Random module*: It generates random numbers in between range based on size


In [ ]:
print(np.random.rand(3,3)) # returns
print(np.random.randint(1,10,size=(3,3)))

[[0.30317613 0.72416591 0.73618802]
 [0.41255077 0.1515707  0.34925445]
 [0.48712516 0.0665783  0.86293134]]
[[6 7 5]
 [3 6 4]
 [5 3 3]]


np.random.rand(): Returns the random numbers between 0-1.

np.random.randint():Returns the random numbers in between the range which were given in paranthesis..

**Performance Optimization with NumPy**

*Implementation*: The core functionalities of NUMPY is implemented in c language.

*Avoiding loops*: Use vectorized computations instead of loops for fast processing..

*contiguous memory*: Arrays stored in contiguous memory blocks can be processed faster.

**NUMPY for data analysis**

Overall NumPy is a fundamental package for data analysis in Python. It provides support for large, multi-dimensional arrays and matrices, along with a vast collection of mathematical functions to operate on these arrays. NumPy is essential for numerical computing and serves as the foundation for many other data science libraries like Pandas, SciPy, and Scikit-learn.